language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install --prefer-dist --dev
  - curl https://raw.github.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=3.6.1 bash

after_script:
  - php vendor/bin/coveralls -v
